language: ruby
jdk: oraclejdk8
rvm: 2.2
before_install: gem install jekyll
script: ant -buildfile build.xml travis-publish-ig -Dguidename=qicore -Dspec=http://hl7-fhir.github.io/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: output
  on:
    branch: master

env:
  global:
    - GH_COMMIT_AUTHOR="Travis CI"
    - GH_COMMIT_EMAIL=travisci@travisci.org
    - ENCRYPTION_LABEL=ddaacfe268bd

notifications:
  email:
    - raj.muthukkannan@wolterskluwer.com
